#!/bin/bash
# Elektronisches Klassenbuch
# nutzt Namensliste (ohne .local) im Verzeichnis
# Klassenbuch im home directory
# Output Konsole + File datum-klasse
# needs tput
#
# nr@bulme.at 2018

grey=`tput setaf 7`
red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

if [ "$#" -ne 1 ]; then
	echo "./klabu <klasse>"
	exit 1
fi

klasse=$1
printf "\nping auf hosts in Klasse $klasse:\n\n"

cat ~/Klassenbuch/$klasse |
(while read name; do
	[ -z "$name" ] && continue
	if result=$(ping $name.local -c 1 -W 1  2>/dev/null | grep from); then
	        ip=$(echo $result | awk  '{print $4}')
	       	printf '%-30s\t%-25s\n' "${green}"$name $ip
	else
	       	printf '%-30s\t%-25s\n' "${red}"$name "fehlt"
	fi
done 
echo ${reset}) |
tee  ~/Klassenbuch/$(date "+%Y-%m-%d")-$klasse


