#!/bin/bash
# Edgar Neukirchner 2016
#
# Configure a fresh raspbian jessie on a mounted SD-Card
# using a usb sd card adaptor on a Raspberry.
# USE AT YOUR OWN RISK!
#
# Script configures hostname, wlan access 
#
# Tested on ubuntu 17.10
############################################
# Change these lines according to your wifi config:
#
SSID="raspinet"
PASS="raspi2016"
#
############################################
# fdisk -l | grep sd
# echo -n "Enter device to use: "
# read device


echo -n "Hostname: "
read new_hostname

base=$(mount | grep media | cut -d " " -f3 | grep -v boot)
bootbase=$(mount | grep media | cut -d " " -f3 | grep boot)

if [ ! -d $base ] ; then
    echo "$base does not exist"
    exit 1
fi
if [ ! -d $bootbase ] ; then
    echo "$bootbase does not exist"
    exit 1
fi


echo $new_hostname > $base/etc/hostname
sed -i "s/127.0.1.1.*raspberrypi/127.0.1.1\t$new_hostname/g" $base/etc/hosts

cat << EOF > $base/etc/wpa_supplicant/wpa_supplicant.conf
country=AT
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
    ssid="$SSID"
    psk="$PASS"
}
EOF

# keep wifi from falling asleep
cat << EOF >> $base/etc/network/interfaces 
wireless-power off
wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
EOF

# static nameserver needed in our intranet
cat << EOF >> $base/etc/dhcpcd.conf 
static domain_name_servers=8.8.8.8
EOF

# enable ssh server
touch $bootbase/ssh

umount $base
umount $bootbase
echo "configuration finished"


